/**
 * Documentation Generator for Cyclos
 * Generates technical sitemap and developer guide for Timely Hub team
 */

import * as fs from 'fs';
import * as path from 'path';

// Project metadata
const projectTitle = "CYCLOS: Zero-Latency Radial Synthesizer";
const version = "1.0.0";
const company = "Timely Hub";

// Architecture overview - Physics-first engineering approach
const architectureOverview = `
## 🏗 High-Performance Architecture

Cyclos is built on a "Tri-Thread" model to ensure professional musical performance:

1. **The Real-Time Thread (C++/JSI):** Handles the Waveform Superposition and Oscillator Pool. Bypasses the React Native Bridge for <1ms execution.
2. **The Render Thread (Skia/GLSL):** GPU-accelerated canvas using GLSL shaders for fluid 60FPS visual feedback.
3. **The Logic Thread (MERN/Zustand):** Manages high-level state, scale theory, and user preferences.

### Physics Foundation

- **Waveform Superposition:** y_total = Σy_i (additive synthesis)
- **Latency Oracle:** Phase-shifting visual pulses to match Bluetooth propagation delays
- **Voice Stealing:** Oldest oscillator with lowest amplitude gets reassigned for polyphony
- **Zero-Crossing:** Anti-pop protection for smooth note on/off
`;

// Technical sitemap
const projectSitemap = `
## 🗺 Technical Sitemap

### Core Architecture
- **/src/native** - C++ JSI Oscillator implementations (The "Engine")
- **/src/shaders** - GLSL ripple and glow effects (The "Vibe")
- **/src/hooks** - Latency Oracle and Audio-Visual Sync logic
- **/src/store** - Zustand stores for scale theory and persistent telemetry

### Components
- **/src/components/canvas** - Skia-based high-performance grid rendering
- **/src/components/grid** - Multiple grid layouts (CircularGrid, PianoRow, etc.)
- **/src/components/keys** - NoteCircle, MusicKey interactive components
- **/src/components/ui** - Overlays, settings, calibration wizards

### Audio System
- **/src/lib/audio/NativeAudio.ts** - Native bridge for audio engine
- **/src/lib/audio/AudioLoader.ts** - Sound file management
- **/src/lib/audio/AudioContextWarmup.ts** - Audio context initialization

### Performance
- **/src/lib/performance/MobileAudioMonitor.ts** - Latency tracking
- **/src/lib/performance/PerformanceMonitor.ts** - FPS and render metrics

### Utilities
- **/src/lib/math.ts** - MIDI to frequency conversion, music theory
- **/src/lib/geometry.ts** - Polar/Cartesian coordinate transforms
`;

// Physics and audio theory documentation
const physicsTheory = `
## 🎵 Audio Physics & Music Theory

### Frequency Calculation
\`\`\`typescript
// A440 Tuning Standard (ISO 16)
// Formula: f = 440 * 2^((n - 69) / 12)
midiToFrequency(midi: number): number
frequencyToMidi(frequency: number): number
\`\`\`

### Note Naming
- MIDI 69 = A4 (440Hz)
- Chromatic scale: C, C#, D, D#, E, F, F#, G, G#, A, A#, B
- Black keys detected via modulo-12 pattern: [1, 3, 6, 8, 10]

### Latency Compensation
- Wired/Bluetooth classification for sync adjustment
- Measured latency stored in AsyncStorage
- Visual phase offset applied via Reanimated \`withDelay\`
`;

// Development setup
const devSetup = `
## 🔧 Development Setup

### Prerequisites
- Node.js 18+
- Expo SDK 54+
- Android Studio / Xcode for native builds

### Installation
\`\`\`bash
npm install
npm install -D jest-expo @testing-library/react-native
\`\`\`

### Running Tests
\`\`\`bash
npm test           # Watch mode
npm run test:ci    # CI mode
\`\`\`

### Building
\`\`\`bash
npx expo prebuild  # Generate native directories
npx expo run:android
npx expo run:ios
\`\`\`
`;

// Performance benchmarks
const performance = `
## ⚡ Performance Benchmarks

| Metric | Target | Current |
|--------|--------|---------|
| Audio Latency (JSI) | < 1ms | ~10ms (Bridge) |
| Visual Latency | < 16ms | 16.6ms (60fps) |
| Touch-to-Sound | < 10ms | 20-50ms |
| Polyphony | 8 voices | 8 voices |
| Memory Usage | < 100MB | TBD |

### Optimization Strategies
1. **JSI Integration:** Bypass React Native bridge for audio
2. **Skia Rendering:** GPU-accelerated canvas for 60fps
3. **Voice Pool:** Pre-warmed GC oscillators prevent jitter
4. **LRU Cache:** Unload unused audio samples
`;

// Build the final documentation
const documentation = `# ${projectTitle}

**Version:** ${version}  
**Company:** ${company}  
**Description:** Zero-latency radial synthesizer with physics-based audio engine

---

${architectureOverview}

${projectSitemap}

${physicsTheory}

${devSetup}

${performance}

---

## 🚀 CEO Launch Checklist

- [ ] Stress test polyphony (12+ rapid taps)
- [ ] Verify sync oracle with Bluetooth 5.0 and 4.2
- [ ] Skia profiling (ensure ripple < 16.6ms/frame)
- [ ] Test calibration wizard on multiple devices
- [ ] Verify dark/light theme accessibility

---

*Generated by Timely Hub Documentation System*
`;

// Write the documentation
const outputPath = path.join(process.cwd(), 'DEVELOPER_GUIDE.md');
fs.writeFileSync(outputPath, documentation);

console.log(`
╔════════════════════════════════════════════════════════════╗
║  ✅ DEVELOPER GUIDE GENERATED SUCCESSFULLY                  ║
╠════════════════════════════════════════════════════════════╣
║  File: ${outputPath}                               ║
║  Title: ${projectTitle}              ║
║  Version: ${version}                                             ║
╚════════════════════════════════════════════════════════════╝
`);

// Also generate a quick reference card
const quickRef = `
# Quick Reference

## Key Commands
\`\`\`bash
npm test              # Run tests
npx expo start        # Start dev server
npx expo prebuild     # Generate native dirs
\`\`\`

## Key Files
| File | Purpose |
|------|---------|
| src/hooks/useAudioEngine.ts | Audio playback control |
| src/components/keys/NoteCircle.tsx | Interactive note component |
| src/lib/math.ts | MIDI/Frequency conversion |
| src/store/useAppStore.ts | Global state management |

## Audio Latency Tuning
1. Open Settings > Calibrate Audio
2. Tap when you hear the beep
3. System measures: t_touch - t_emitted - 150ms (reaction)
4. Saves offset for future sessions
`;

const quickRefPath = path.join(process.cwd(), 'QUICK_REFERENCE.md');
fs.writeFileSync(quickRefPath, quickRef);

console.log(`✅ Quick Reference generated: ${quickRefPath}`);
